// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    BlockDragger: typeof import('./components/editor/BlockDragger.vue')['default']
    CommentEditor: typeof import('./components/editor/CommentEditor.vue')['default']
    CommentItem: typeof import('./components/comment/CommentItem.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ICarbonFaceAdd: typeof import('~icons/carbon/face-add')['default']
    ICarbonImage: typeof import('~icons/carbon/image')['default']
    ICarbonNotification: typeof import('~icons/carbon/notification')['default']
    ICarbonNotificationFilled: typeof import('~icons/carbon/notification-filled')['default']
    ICarbonOverflowMenuVertical: typeof import('~icons/carbon/overflow-menu-vertical')['default']
    ICarbonSearch: typeof import('~icons/carbon/search')['default']
    MarkdownShortcutPlugin: typeof import('./components/editor/plugins/MarkdownShortcutPlugin.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCol: typeof import('naive-ui')['NCol']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NProvider: typeof import('./components/NProvider.vue')['default']
    NRow: typeof import('naive-ui')['NRow']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    PostEditor: typeof import('./components/editor/PostEditor.vue')['default']
    PostFooterAction: typeof import('./components/post/PostFooterAction.vue')['default']
    PostHeaderAction: typeof import('./components/post/PostHeaderAction.vue')['default']
    PostHeaderUser: typeof import('./components/post/PostHeaderUser.vue')['default']
    PostItem: typeof import('./components/post/PostItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
