-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" bigint NOT NULL, "updated_at" bigint NOT NULL, "deleted_at" bigint NULL DEFAULT 0, "username" character varying NOT NULL, "nickname" character varying NOT NULL DEFAULT '', "password" character varying NOT NULL, "salt" character varying NOT NULL, "status" smallint NOT NULL DEFAULT 0, "avatar" character varying NOT NULL DEFAULT '', "is_admin" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"));
-- create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- create index "user_created_at" to table: "users"
CREATE INDEX "user_created_at" ON "users" ("created_at");
-- create index "user_deleted_at" to table: "users"
CREATE INDEX "user_deleted_at" ON "users" ("deleted_at");
-- create "posts" table
CREATE TABLE "posts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" bigint NOT NULL, "updated_at" bigint NOT NULL, "deleted_at" bigint NULL DEFAULT 0, "comment_count" bigint NOT NULL DEFAULT 0, "visibility" smallint NOT NULL DEFAULT 0, "latest_replied_at" bigint NOT NULL DEFAULT 0, "ip" character varying NOT NULL DEFAULT '', "ip_loc" character varying NOT NULL DEFAULT '', "content" jsonb NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "posts_users_posts" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION);
-- create index "post_created_at" to table: "posts"
CREATE INDEX "post_created_at" ON "posts" ("created_at");
-- create index "post_deleted_at" to table: "posts"
CREATE INDEX "post_deleted_at" ON "posts" ("deleted_at");
-- create index "post_user_id" to table: "posts"
CREATE INDEX "post_user_id" ON "posts" ("user_id");
-- create "comments" table
CREATE TABLE "comments" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" bigint NOT NULL, "updated_at" bigint NOT NULL, "deleted_at" bigint NULL DEFAULT 0, "ip" character varying NOT NULL DEFAULT '', "ip_loc" character varying NOT NULL DEFAULT '', "content" jsonb NOT NULL, "post_id" bigint NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "comments_posts_comments" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE NO ACTION, CONSTRAINT "comments_users_comments" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION);
-- create index "comment_created_at" to table: "comments"
CREATE INDEX "comment_created_at" ON "comments" ("created_at");
-- create index "comment_deleted_at" to table: "comments"
CREATE INDEX "comment_deleted_at" ON "comments" ("deleted_at");
